import { Order, UserProfile } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Bapak Heru Setiawan',
  memberId: '#CL-88294-HS',
  email: 'heru.setiawan@email.com',
  phone: '+62 812-3456-7890',
  savedAddressLabel: 'Rumah Utama',
  savedAddressDetails: 'Jl. Melati No. 12, Komplek Permata Hijau, Kec. Kebayoran Lama, Jakarta Selatan, 12210',
  memberLevel: 'PREMIUM MEMBER',
  totalOrders: 14,
  totalSpending: 450000,
  progressSpending: 450000,
  targetSpending: 1000000,
};

export const SERVICES = [
  {
    id: 'regular',
    name: 'Regular Laundry',
    price: 7000,
    unit: 'kg',
    estimate: 'Estimasi 2-3 Hari',
    desc: 'Cuci bersih, kering, setrika, rapi',
    icon: 'dry_cleaning',
  },
  {
    id: 'express',
    name: 'Express Laundry',
    price: 15000,
    unit: 'kg',
    estimate: 'Estimasi 24 Jam',
    desc: 'Layanan kilat super cepat',
    icon: 'bolt',
  },
  {
    id: 'shoes',
    name: 'Shoes Cleaning',
    price: 35000,
    unit: 'psg',
    estimate: 'Pembersihan Deep-clean',
    desc: 'Spesialis cuci sepatu kotor',
    icon: 'footprint',
  },
  {
    id: 'carpet',
    name: 'Carpet Laundry',
    price: 20000,
    unit: 'm²',
    estimate: 'Pembersihan Spesialis',
    desc: 'Bersih tuntas dari tungau & debu',
    icon: 'layers',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: '#ORD-8924',
    serviceName: 'Reguler (2-3 Hari) + Layanan Khusus',
    weight: 5.0,
    orderDate: '24 Okt 2023',
    orderTime: '09:42 AM',
    status: 'Pencucian',
    statusLabelIndo: 'Sedang Dicuci',
    totalPrice: 60000,
    paymentMethod: 'QRIS',
    paymentStatus: 'LUNAS',
    pickupAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    deliveryAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    pickupTimeLabel: '24 Okt, 11:30',
    readyTimeLabel: '26 Okt, 10:00',
    notes: 'Pisahkan kemeja putih dari pakaian berwarna gelap. Setrika rapi.',
    platformFee: 2000,
    discount: 5000,
    kurirName: 'Budi Santoso',
    kurirEtaMinutes: 5,
    kurirPhone: '+62 878-1122-3344',
    items: [
      {
        id: 'item-1',
        name: 'Kemeja Pria (Kantor)',
        type: 'Atasan',
        quantity: '3 Pcs',
        treatment: 'KAJI + SETRIKA',
        priceUnit: 'Rp 5.000',
        subtotal: 15000,
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkeyo6RXdx3-I9IV4goGxSGxvUQuAMtk6Rb-hAZUCURPbU41SdsQ6rcP_Wer58M1dLlJoMEA8J1ITjxeX__tX9WhGSn2NZGziQSHOvy7WNHHwpLkhYzjXif-dgrj4nS664PXZHyU9mxu5z2xFMFPeTZJ3045KrZCeox1vBXAbncKvrvxCfqwj8Q-5fNPbPjhvE_K6SDnZxv7gQfddodI2ZYxv5nv2mEAkAyNzDSEEvahuLYAJvybnB49p28laVWz9zLjytgiK6JQIq',
      },
      {
        id: 'item-2',
        name: 'Celana Jeans',
        type: 'Bawahan',
        quantity: '2 Pcs',
        treatment: 'CUCI STANDAR',
        priceUnit: 'Rp 7.500',
        subtotal: 15000,
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAVD9Eyu6CLN6HKMuKe-DHzzJ4jNLNeABMXd1n-WvaW60TaGRq1_yKaghlOuOP5AQqq4u0lsjFq5jRyOgZnJwGslpUVT0W4UGIMEsvqZDt8qJ3-khj0yclNmsgrxJw789sGx48b9iQyUE9atnTa7OMTZb7VxA55X6MkzlQdE895_EW5HkXq60lmo4SgXvaDonkIAE6Geiu9DVQAmycaEM8Fk124muKCiuWCFPKPn-2S2Vjj4j8dKXvmP7T67yFhGw7oSLciem1_xbz-',
      },
      {
        id: 'item-3',
        name: 'Laundry Kiloan Campur',
        type: 'Kiloan',
        quantity: '5.2 KG',
        treatment: 'KILOAN REGULER',
        priceUnit: 'Rp 3.000/kg',
        subtotal: 15600,
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQ-hhB2jVfigfG88Mrf_eZnDotxwFDxSxKkqaNlNaJYf3wU38lbxlUcJGc1qgPs01TQ4418-2myZeEUK_HVcsXOAa4eryxKt-odNMfZ5stnuGuCLfO8BvxOa7f_7KNF9A2pWGL4dDqYLTCjLiUMqWl-kEgTJ1FTDj7KBc5pMy9-TjbpZW2Nb0qmYDMWF_eyUFqAcnCVVuct88AeXU8P1y4VoA0oibgsgg10nro-GbFHDQZkHkNP_L_xsQFWWDzSTEmGrg7oBnX6Vxw',
      }
    ]
  },
  {
    id: '#ORD-8821',
    serviceName: 'Laundry Express',
    weight: 3.0,
    orderDate: '24 Okt 2023',
    orderTime: '08:00 AM',
    status: 'Pencucian',
    statusLabelIndo: 'Sedang Dicuci',
    totalPrice: 45000,
    paymentMethod: 'Tunai',
    paymentStatus: 'BELUM BAYAR',
    pickupAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    deliveryAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    pickupTimeLabel: '24 Okt, 09:30',
    readyTimeLabel: '25 Okt, 09:30',
    notes: 'Gunakan deterjen bayi dan jangan memakai pewangi menyengat.',
    platformFee: 0,
    discount: 0,
    kurirName: 'Ahmad Sopian',
    kurirEtaMinutes: 10,
    items: [
      {
        id: 'item-1',
        name: 'Pakaian Bayi & Linen',
        type: 'Kiloan',
        quantity: '3.0 KG',
        treatment: 'CUCI EXPRESS',
        priceUnit: 'Rp 15.000/kg',
        subtotal: 45000,
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQ-hhB2jVfigfG88Mrf_eZnDotxwFDxSxKkqaNlNaJYf3wU38lbxlUcJGc1qgPs01TQ4418-2myZeEUK_HVcsXOAa4eryxKt-odNMfZ5stnuGuCLfO8BvxOa7f_7KNF9A2pWGL4dDqYLTCjLiUMqWl-kEgTJ1FTDj7KBc5pMy9-TjbpZW2Nb0qmYDMWF_eyUFqAcnCVVuct88AeXU8P1y4VoA0oibgsgg10nro-GbFHDQZkHkNP_L_xsQFWWDzSTEmGrg7oBnX6Vxw',
      }
    ]
  },
  {
    id: '#ORD-8710',
    serviceName: 'Cuci Karpet',
    weight: 6.0,
    orderDate: '20 Okt 2023',
    orderTime: '10:15 AM',
    status: 'Selesai',
    statusLabelIndo: 'Selesai',
    totalPrice: 120000,
    paymentMethod: 'QRIS',
    paymentStatus: 'LUNAS',
    pickupAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    deliveryAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    pickupTimeLabel: '20 Okt, 11:00',
    readyTimeLabel: '23 Okt, 16:00',
    platformFee: 2000,
    discount: 0,
    items: [
      {
        id: 'item-1',
        name: 'Karpet Bulu Tebal',
        type: 'Karpet',
        quantity: '6.0 m²',
        treatment: 'CUCI SPESIALIS',
        priceUnit: 'Rp 20.000/m²',
        subtotal: 120000,
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCx9A7zYG8OALjhvJWoC8v8kND-7kvowwxpGRKOPxOZTdVwwPCJoTc438qrd7JZE3ET8m0JQof46mfH5HH1EjLXuhqMs_EE3eOMYeV6rXD81beoWORUcuqU9gtc1vajs-Vm9K9UXbdVbpx-EGCAsqP6ZrQoHSIDOmw3RnlsBAE4Y7K-YISe2lJe6tx0WBJ73NSYjx_yBiaQ9ohJX7r8MGMxhmZkTfyFd-ahHWqlASJVnzf48QEV-se8Zo5MFAuu4PHE39i8VeCKQapS',
      }
    ]
  },
  {
    id: '#ORD-8655',
    serviceName: 'Regular Laundry',
    weight: 4.5,
    orderDate: '18 Okt 2023',
    orderTime: '11:20 AM',
    status: 'Selesai',
    statusLabelIndo: 'Selesai',
    totalPrice: 31500,
    paymentMethod: 'Tunai',
    paymentStatus: 'LUNAS',
    pickupAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    deliveryAddress: 'Apartemen Green Park, Tower A, Unit 12B, Jakarta Selatan',
    pickupTimeLabel: '18 Okt, 13:00',
    readyTimeLabel: '21 Okt, 15:00',
    platformFee: 0,
    discount: 0,
    items: [
      {
        id: 'item-1',
        name: 'Pakaian Harian Campur',
        type: 'Kiloan',
        quantity: '4.5 KG',
        treatment: 'KILOAN REGULER',
        priceUnit: 'Rp 7.000/kg',
        subtotal: 31500,
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQ-hhB2jVfigfG88Mrf_eZnDotxwFDxSxKkqaNlNaJYf3wU38lbxlUcJGc1qgPs01TQ4418-2myZeEUK_HVcsXOAa4eryxKt-odNMfZ5stnuGuCLfO8BvxOa7f_7KNF9A2pWGL4dDqYLTCjLiUMqWl-kEgTJ1FTDj7KBc5pMy9-TjbpZW2Nb0qmYDMWF_eyUFqAcnCVVuct88AeXU8P1y4VoA0oibgsgg10nro-GbFHDQZkHkNP_L_xsQFWWDzSTEmGrg7oBnX6Vxw',
      }
    ]
  }
];
